name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate IB version tag
        id: version
        run: |
          res=$(curl -s https://download2.interactivebrokers.com/installers/ibgateway/${{ matrix.channel }}-standalone/version.json)
          build_version=$(grep -oP '(?<=buildVersion":")[^"]+' <<< "$res")
          echo "build_version=$build_version" >> $GITHUB_OUTPUT

      -
        name: Generate Date Based tag
        id: gen_tag
        run: |
          date_tag=$(printf '%(%Y%m%d%H%M%S)T\n' -1)
          echo "date_tag=$date_tag" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
              riazarbi/ib-headless:${{ steps.version.outputs.build_version }}
              riazarbi/ib-headless:${{ steps.gen_tag.outputs.date_tag }}
              riazarbi/ib-headless:latest
