name: Build new docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate IB version tag
        id: version
        run: |
          res=$(curl -s https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/version.json)
          IB_TAG=$(grep -oP '(?<=buildVersion":")[^"]+' <<< "$res")
          echo '::set-output name=ib_tag::'$IB_TAG

      -
        name: Generate tag
        id: gen_tag
        run: |
          DATE_TAG=$(printf '%(%Y%m%d%H%M%S)T\n' -1)
          echo '::set-output name=date_tag::'$DATE_TAG
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
              riazarbi/ib-headless:${{ fromJson(steps.gen_tag.outputs.ib_tag) }}
              riazarbi/ib-headless:${{ fromJson(steps.gen_tag.outputs.date_tag) }}
              riazarbi/ib-headless:latest
